### ISSUE TITLE
Kernel-6.1.43-joshua-panthor No WiFi Available - WiFi Module - RTL8852BE-CG CPU

### ISSUE THREAD

**Issue by JFLim1** [kwankiu/PKGBUILDs#1]
Hi @kwankiu,

Just a feedback, cannot seems to get WiFi enabled when using inux-aarch64-rockchip-bsp6.1-joshua-panthor-git 6.1.43.r1266142.6bd0bc64-1.  The system seems to try to load the WiFI but it always failed to connect.

With linux-aarch64-rockchip-bsp5.10-joshua 5.10.160.34-1 WiFI is available and function as expected.

```
38.841461] wlP2p33s0: authenticate with 34:e8:94:75:06:72
[   39.037189] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 1/3)
[   39.051737] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 2/3)
[   39.066437] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 3/3)
[   39.081054] wlP2p33s0: authentication with 34:e8:94:75:06:72 timed out
[   42.907876] wlP2p33s0: authenticate with 34:e8:94:75:06:72
[   43.093412] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 1/3)
[   43.108119] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 2/3)
[   43.123013] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 3/3)
[   43.137585] wlP2p33s0: authentication with 34:e8:94:75:06:72 timed out
[   72.552382] wlP2p33s0: authenticate with 34:e8:94:75:06:72
[   72.740349] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 1/3)
[   72.754863] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 2/3)
[   72.769516] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 3/3)
[   72.784112] wlP2p33s0: authentication with 34:e8:94:75:06:72 timed out
[   77.451215] wlP2p33s0: authenticate with 34:e8:94:75:06:72
[   77.640365] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 1/3)
[   77.654929] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 2/3)
[   77.669534] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 3/3)
[   77.684145] wlP2p33s0: authentication with 34:e8:94:75:06:72 timed out
[   87.365892] wlP2p33s0: authenticate with 34:e8:94:75:06:72
[   87.558292] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 1/3)
[   87.573136] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 2/3)
[   87.587740] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 3/3)
[   87.602389] wlP2p33s0: authentication with 34:e8:94:75:06:72 timed out
[  101.374920] wlP2p33s0: authenticate with 34:e8:94:75:06:72
[  101.564182] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 1/3)
[  101.578960] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 2/3)
[  101.593897] wlP2p33s0: send auth to 34:e8:94:75:06:72 (try 3/3)
[  101.608475] wlP2p33s0: authentication with 34:e8:94:75:06:72 timed out
```

![image](https://github.com/kwankiu/PKGBUILDs/assets/75384411/0145f6a4-675b-4365-8217-c92674df9526)

Checking whether other Opi5-Plus users with WiFi module RTL8852BE-CG managed to connect to WiFi when running on linux-aarch64-rockchip-bsp6.1-joshua-panthor-git 6.1.43.r1266142.6bd0bc64-1?

**Comment by kwankiu** [comment]
Hmm interesting, is there any similar issues with Joshua’s Ubuntu Image?

Since 8852BE works well on the Rock 5B

**Comment by kwankiu** [comment]
So that the WiFi driver loaded but it was unable to connect to WiFi.

Are you connecting WiFi with GUI (from a Desktop Environment) or from command line?

does using nmtui or WiFi-menu or iwd make a difference?

**Comment by kwankiu** [comment]
nmtui should results the same with the GUI NetworkManager, see if WiFi-menu and iwd is able to connect to WiFi, you can also try set WiFi-backend of NetworkManager to iwd

**Comment by kwankiu** [comment]
> > Hmm interesting, is there any similar issues with Joshua’s Ubuntu Image?
> 
> With the old Joshua Ubuntu-22.04.3 with kernel 6.1.43 (build #249, if not mistaken), had the same issue it cannot connect to WiFi, network manager will try to connect WiFi but will timeout and fail and it will retry and retry. Had not try Joshua Ubuntu-Noble 24.04 with kernel 6.1.43 yet. Waiting for it to be releases or his official beta release.
> 
> > Since 8852BE works well on the Rock 5B
> 
> Is there a difference between Opi5-Plus RTL8852BE-CG and Rock 5B RTL8852BE?
> 
> > So that the WiFi driver loaded but it was unable to connect to WiFi.
> 
> Yes, WiFi driver is loaded. The question is it the correct WiFi driver?
> 
> ```
> lsmod
> rtw_8852be             16384  0
> rtw_8852b             356352  1 rtw_8852be
> rtw89pci               53248  1 rtw_8852be
> pwm_fan                20480  0
> rtw89core             454656  2 rtw89pci,rtw_8852b
> r8125                 188416  0
> ```
> 
> It will go into loop trying to connect and failed to connect and retry again and again. At least with linux-aarch64-rockchip-bsp6.1-joshua-panthor-git 6.1.43 and mesa-panfrost-git on KDE-Plasma Desktop it does NOT crash the Plasmashell or Plasma Panel.
> 
> With linux-aarch64-rockchip-bsp6.1-joshua-git and mesa-panfork-git, this looping/retry to connect WiFi but failed after one or two tries, it will crash Plasmashell or Plasma Panel.
> 
> > Are you connecting WiFi with GUI (from a Desktop Environment) or from command line?
> 
> Am on KDE-Plasma DE.with plasma-nm installed.
> 
> > does using nmtui or WiFi-menu or iwd make a difference?
> 
> Just attempted to connect WiFi using nmtui and it failed to connect.
> 
> `Could not activate connection: Activation failed. The Wi-Fi network could be found.`
> 
> Not sure why the WiFi timeout and refuse to connect.
> 
> No issue with WiFi connection on Joshua's kernel-5.10.160.34 or linux-aarch64-rockchip-rk3588-bsp5.10-orangepi-git 5.10.160 (from 7Ji-Repo) or any of the bsp-kernel-5.10 for orangepi5.

Btw if this issue happens on Joshua’s 6.1 kernel and on his Ubuntu image, better discuss in Joshua’s GitHub issue. Check if there is a related discussion there, if not, open a new issue I guess.

**Comment by JFLim1** [comment]
> Btw if this issue happens on Joshua’s 6.1 kernel and on his Ubuntu image, better discuss in Joshua’s GitHub issue. Check if there is a related discussion there, if not, open a new issue I guess.

Thanks.  When Joshua beta-releases Ubuntu-24.04-6.1.43 will test it then.

**Comment by JFLim1** [comment]
Just a feedback.  chromium-mpp vpu hw acceleration works with  6.1.43-joshua-panthor-git and mesa-panfrost-git (Opi5-Plus).

**Comment by JFLim1** [comment]
> But I am curious why would Panfork and Panthor gives a different to plasma shell regarding to KDE’s network manager

Hi @kwankiu,

Sorry missed this comment earlier.  For the record running KDE Plasma 6 Wayland (also on KDE Plasma 5.27.10) with panfork at times encounter Plasmashell/Plasma Panel crashes at times seemingly random but quite offend can be induced.   Did encounter similar Plasmashell/Plasma Panel crashes on Plasma-X11.

One of the way to induce Plasmashell crash when on kernel-6.1 and "panfork", is to enable WiFi.  The system will try to connect WiFi and it will fail to connect.  When it failed to connect a "small window" with "failed connection" will pop-up. The system will try to reconnect and another "pop-up message of failed connection" and after one or two retry with "pop-up message" Plasmashell will crash.

With Panthor the retry and pop-up message of failed connection and repetition does NOT crash Plasmashell.  In this sense Panthor is more robust on KDE Plasma.

Gnome with kernel-6.1 and panfork also does NOT will not crash due to repeated failed WiFi connection.

**Comment by JFLim1** [comment]
Hi @kwankiu,

Just an update: Received an updated from Joshua Riek on RTL8852BE support for Opi5-Plus:

> It will work, I had to upgrade the driver to support loading compressed firmware. However, I'm still waiting for Ubuntu to finish building packages for the Beta so there is not much I can do right now.

Can it be implemented in Archlinux?
